# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('healthNet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthNet.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 5, 21, 10, 25, 511358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2016, 12, 4, 22, 10, 25, 511358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 5, 21, 10, 25, 511358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicalnotes',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 21, 10, 25, 504838, tzinfo=utc)),
        ),
    ]
